version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: teachspace
      POSTGRES_USER: masterpiece
      POSTGRES_PASSWORD: zntPEGASUS77K
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: